name: generator

on:
  push:
    branches: [master]

  workflow_dispatch:

concurrency: 
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"

    steps:
      - uses: actions/checkout@v3.1.0
      - name: Generate RSS for Data Privacy
        uses: opensource-f2f/open-podcasts@master
        with:
          output: podcasts/data-privacy/index.rss
          showFile: podcasts/data-privacy/show.yaml
          itemsPattern: podcasts/data-privacy/item-*.yaml
          server: "fake"
      - name: Generate RSS for remote jobs
        uses: opensource-f2f/open-podcasts@master
        with:
          output: podcasts/remote-jobs/index.rss
          showFile: podcasts/remote-jobs/show.yaml
          itemsPattern: podcasts/remote-jobs/item-*.yaml
          server: "fake"
      - name: Generate RSS for Podcasts guide
        uses: opensource-f2f/open-podcasts@master
        with:
          output: podcasts/podcasts-guide/index.rss
          showFile: podcasts/podcasts-guide/show.yaml
          itemsPattern: podcasts/podcasts-guide/item-*.yaml
          server: "fake"
      - name: Generate RSS for Open Source Community
        uses: opensource-f2f/open-podcasts@master
        with:
          output: podcasts/os-community/index.rss
          showFile: podcasts/os-community/show.yaml
          itemsPattern: podcasts/os-community/item-*.yaml
          server: "fake"
      - name: Update readme
        uses: linuxsuren/yaml-readme@v0.0.13
        env:
          GH_TOKEN: ${{ secrets.GH_SECRETS }}
        with:
          pattern: 'podcasts/*/show.yaml'
          output: podcasts.md
          template: podcasts.tpl
          username: linuxsuren
          org: linuxsuren
          repo: awesome-feeds
          push: false
      - name: Update readme
        uses: linuxsuren/yaml-readme@v0.0.13
        env:
          GH_TOKEN: ${{ secrets.GH_SECRETS }}
        with:
          pattern: 'data/*.yaml'
          username: linuxsuren
          org: linuxsuren
          repo: awesome-feeds
          groupby: kind
